package com.littlecloud.control.entity.report;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.EmbeddedId;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.peplink.api.db.DBObject;

/**
 * DailyClientUsages generated by hbm2java
 */
@Entity
@Table(name = "daily_client_usages")
public class DailyClientUsages extends DBObject implements java.io.Serializable {
	private DailyClientUsagesId id;
	private int deviceId;
	private int networkId;
	private String mac;
	private String name;
	private String manufacturer;
	private Float tx;
	private Float rx;
	private String ip;
	private Date datetime;
	private String type;

	public DailyClientUsages() {
		id = new DailyClientUsagesId();
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "unixtime", column = @Column(name = "unixtime", nullable = false)) })
	public DailyClientUsagesId getId() {
		return this.id;
	}

	public void setId(DailyClientUsagesId id) {
		this.id = id;
	}

	@Column(name = "device_id")
	public int getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "network_id", nullable = false)
	public int getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(int networkId) {
		this.networkId = networkId;
	}

	@Column(name = "mac", nullable = false, length = 45)
	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "manufacturer", length = 45)
	public String getManufacturer() {
		return manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "tx", precision = 12, scale = 0)
	public Float getTx() {
		return this.tx;
	}

	public void setTx(Float tx) {
		this.tx = tx;
	}

	@Column(name = "rx", precision = 12, scale = 0)
	public Float getRx() {
		return this.rx;
	}

	public void setRx(Float rx) {
		this.rx = rx;
	}
	
	@Column(name = "ip", length=32)
	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getUnixtime() {
		return id.getUnixtime();
	}

	public void setUnixtime(Integer unixtime) {
		id.setUnixtime(unixtime);
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DailyClientUsages [id=");
		builder.append(id);
		builder.append(", deviceId=");
		builder.append(deviceId);
		builder.append(", networkId=");
		builder.append(networkId);
		builder.append(", mac=");
		builder.append(mac);
		builder.append(", name=");
		builder.append(name);
		builder.append(", manufacturer=");
		builder.append(manufacturer);
		builder.append(", tx=");
		builder.append(tx);
		builder.append(", rx=");
		builder.append(rx);
		builder.append(", ip=");
		builder.append(ip);
		builder.append(", datetime=");
		builder.append(datetime);
		builder.append(", type=");
		builder.append(type);
		builder.append("]");
		return builder.toString();
	}

}
