package com.littlecloud.control.entity;

// Generated Jul 19, 2013 6:17:45 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.peplink.api.db.DBObject;

/**
 * NetworkSilencePeriods generated by hbm2java
 */
@Entity
@Table(name = "network_silence_periods")
public class NetworkSilencePeriods extends DBObject implements java.io.Serializable {

	public static enum TARGET_TYPE { all_devices, device_tags }
	
	private int networkId;
	private String start;
	private String end;
	private String targetType;
	private String deviceTags;

	public NetworkSilencePeriods() {
	}

	public NetworkSilencePeriods(int networkId, String start, String end,
			String targetType) {
		this.networkId = networkId;
		this.start = start;
		this.end = end;
		this.targetType = targetType;
	}

	public NetworkSilencePeriods(int networkId, String start, String end,
			String targetType, String deviceTags) {
		this.networkId = networkId;
		this.start = start;
		this.end = end;
		this.targetType = targetType;
		this.deviceTags = deviceTags;
	}

	@Id
	@Column(name = "network_id", unique = true, nullable = false)
	public int getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(int networkId) {
		this.networkId = networkId;
	}

	@Column(name = "start", nullable = false, length = 32)
	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	@Column(name = "end", nullable = false, length = 32)
	public String getEnd() {
		return this.end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	@Column(name = "target_type", nullable = false, length = 45)
	public String getTargetType() {
		return this.targetType;
	}

	public void setTargetType(String targetType) {
		this.targetType = targetType;
	}

	@Column(name = "device_tags", length = 5000)
	public String getDeviceTags() {
		return this.deviceTags;
	}

	public void setDeviceTags(String deviceTags) {
		this.deviceTags = deviceTags;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("NetworkSilencePeriods [networkId=");
		builder.append(networkId);
		builder.append(", start=");
		builder.append(start);
		builder.append(", end=");
		builder.append(end);
		builder.append(", targetType=");
		builder.append(targetType);
		builder.append(", deviceTags=");
		builder.append(deviceTags);
		builder.append("]");
		return builder.toString();
	}

}
