package com.littlecloud.control.entity.report;

// Generated Jun 21, 2013 10:38:37 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.peplink.api.db.DBObject;

/**
 * DevicesChannelUtilizations generated by hbm2java
 */
@Entity
@Table(name = "devices_channel_utilizations")
public class DevicesChannelUtilizations extends DBObject implements java.io.Serializable {

	private String id;
	private int networkId;
	private int deviceId;
	private Date datetime;
	private Integer unixtime;
	private Integer percentage;

	public DevicesChannelUtilizations() {
	}

	public DevicesChannelUtilizations(String id, int networkId, int deviceId) {
		this.id = id;
		this.networkId = networkId;
		this.deviceId = deviceId;
	}

	public DevicesChannelUtilizations(String id, int networkId, int deviceId, Date datetime, Integer unixtime, Integer percentage) {
		this.id = id;
		this.networkId = networkId;
		this.deviceId = deviceId;
		this.datetime = datetime;
		this.unixtime = unixtime;
		this.percentage = percentage;
	}
	
	public DevicesChannelUtilizations(int networkId, int deviceId, Date datetime, Integer unixtime, Integer percentage) {
		this.networkId = networkId;
		this.deviceId = deviceId;
		this.datetime = datetime;
		this.unixtime = unixtime;
		this.percentage = percentage;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "network_id", nullable = false)
	public int getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(int networkId) {
		this.networkId = networkId;
	}

	@Column(name = "device_id", nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "unixtime")
	public Integer getUnixtime() {
		return this.unixtime;
	}

	public void setUnixtime(Integer unixtime) {
		this.unixtime = unixtime;
	}

	@Column(name = "percentage")
	public Integer getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Integer percentage) {
		this.percentage = percentage;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DevicesChannelUtilizations [id=");
		builder.append(id);
		builder.append(", networkId=");
		builder.append(networkId);
		builder.append(", deviceId=");
		builder.append(deviceId);
		builder.append(", datetime=");
		builder.append(datetime);
		builder.append(", unixtime=");
		builder.append(unixtime);
		builder.append(", percentage=");
		builder.append(percentage);
		builder.append("]");
		return builder.toString();
	}

}
