
package com.littlecloud.alert.handler;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlertHandlerImplService", targetNamespace = "http://handler.alert.littlecloud.com/", wsdlLocation = "http://localhost:8080/alertws/ws/AlertByMail?wsdl")
public class AlertHandlerImplService
    extends Service
{

    private final static URL ALERTHANDLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALERTHANDLERIMPLSERVICE_EXCEPTION;
    private final static QName ALERTHANDLERIMPLSERVICE_QNAME = new QName("http://handler.alert.littlecloud.com/", "AlertHandlerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/alertws/ws/AlertByMail?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALERTHANDLERIMPLSERVICE_WSDL_LOCATION = url;
        ALERTHANDLERIMPLSERVICE_EXCEPTION = e;
    }

    public AlertHandlerImplService() {
        super(__getWsdlLocation(), ALERTHANDLERIMPLSERVICE_QNAME);
    }

    public AlertHandlerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALERTHANDLERIMPLSERVICE_QNAME, features);
    }

    public AlertHandlerImplService(URL wsdlLocation) {
        super(wsdlLocation, ALERTHANDLERIMPLSERVICE_QNAME);
    }

    public AlertHandlerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALERTHANDLERIMPLSERVICE_QNAME, features);
    }

    public AlertHandlerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlertHandlerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlertHandler
     */
    @WebEndpoint(name = "AlertHandlerImplPort")
    public AlertHandler getAlertHandlerImplPort() {
        return super.getPort(new QName("http://handler.alert.littlecloud.com/", "AlertHandlerImplPort"), AlertHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlertHandler
     */
    @WebEndpoint(name = "AlertHandlerImplPort")
    public AlertHandler getAlertHandlerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://handler.alert.littlecloud.com/", "AlertHandlerImplPort"), AlertHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALERTHANDLERIMPLSERVICE_EXCEPTION!= null) {
            throw ALERTHANDLERIMPLSERVICE_EXCEPTION;
        }
        return ALERTHANDLERIMPLSERVICE_WSDL_LOCATION;
    }

}
