package com.littlecloud.control.entity;

// Generated Jul 19, 2013 6:17:45 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.peplink.api.db.DBObject;

/**
 * NetworkEmailNotificationsId generated by hbm2java
 */
@Embeddable
public class NetworkEmailNotificationsId extends DBObject implements java.io.Serializable {

	private int networkId;
	private String alertType;
	private String level;

	public NetworkEmailNotificationsId() {
	}

	public NetworkEmailNotificationsId(int networkId, String level) {
		this.networkId = networkId;
		this.level = level;
	}

	@Column(name = "network_id", nullable = false)
	public int getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(int networkId) {
		this.networkId = networkId;
	}

	
	@Column(name = "alert_type", nullable = false, length = 20)
	public String getAlertType() {
		return alertType;
	}

	public void setAlertType(String alertType) {
		this.alertType = alertType;
	}

	@Column(name = "level", nullable = false, length = 45)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NetworkEmailNotificationsId))
			return false;
		NetworkEmailNotificationsId castOther = (NetworkEmailNotificationsId) other;

		return (this.getNetworkId() == castOther.getNetworkId())
				&& 
				(
						(this.getLevel() == castOther.getLevel()) || 
						(this.getLevel() != null && 
							castOther.getLevel() != null && 
							this.getLevel().equals(castOther.getLevel()))
				)
				&&
				(
						(this.getAlertType() == castOther.getAlertType()) || 
						(this.getAlertType() != null && 
							castOther.getAlertType() != null && 
							this.getAlertType().equals(castOther.getAlertType()))
				);
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNetworkId();
		result = 37 * result
				+ (getLevel() == null ? 0 : this.getLevel().hashCode());
		result = 37 * result
				+ (getAlertType() == null ? 0 : this.getAlertType().hashCode());
		
		return result;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("NetworkEmailNotificationsId [networkId=");
		builder.append(networkId);
		builder.append(", alertType=");
		builder.append(alertType);
		builder.append(", level=");
		builder.append(level);
		builder.append("]");
		return builder.toString();
	}


}
