package com.littlecloud.control.entity.branch;

// Generated Jul 19, 2013 12:03:37 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.peplink.api.db.DBObject;

/**
 * Models generated by hbm2java
 */
@Entity
@Table(name = "models",catalog = "littlecloud_branch_production")
public class Models extends DBObject implements java.io.Serializable {

	private int id;
	private String productCode;
	private String modelName;

	public Models() {
	}

	public Models(int id, String productCode) {
		this.id = id;
		this.productCode = productCode;
	}

	public Models(int id, String productCode, String modelName) {
		this.id = id;
		this.productCode = productCode;
		this.modelName = modelName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "product_code", nullable = false, length = 200)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "model_name", length = 200)
	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Models [id=");
		builder.append(id);
		builder.append(", productCode=");
		builder.append(productCode);
		builder.append(", modelName=");
		builder.append(modelName);
		builder.append("]");
		return builder.toString();
	}
}
