package com.littlecloud.control.entity.report;

// Generated Nov 29, 2013 4:01:44 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.peplink.api.db.DBObject;

/**
 * DeviceGpsLocationsDates generated by hbm2java
 */
@Entity
@Table(name = "device_gps_locations_dates")
public class DeviceGpsLocationsDates extends DBObject implements java.io.Serializable {

	private DeviceGpsLocationsDatesId id;
	private boolean consolidated;

	public DeviceGpsLocationsDates() {
	}

	public DeviceGpsLocationsDates(DeviceGpsLocationsDatesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "networkId", column = @Column(name = "network_id", nullable = false)),
			@AttributeOverride(name = "deviceId", column = @Column(name = "device_id", nullable = false)),
			@AttributeOverride(name = "unixtime", column = @Column(name = "unixtime", nullable = false)) })
	public DeviceGpsLocationsDatesId getId() {
		return this.id;
	}

	public void setId(DeviceGpsLocationsDatesId id) {
		this.id = id;
	}

	@Column(name = "consolidated")
	public boolean isConsolidated() {
		return consolidated;
	}

	public void setConsolidated(boolean consolidated) {
		this.consolidated = consolidated;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeviceGpsLocationsDates [id=");
		builder.append(id);
		builder.append(", consolidated=");
		builder.append(consolidated);
		builder.append("]");
		return builder.toString();
	}
}
