package com.littlecloud.control.entity.branch;

// Generated Jun 27, 2013 8:32:19 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.peplink.api.db.DBObject;

/**
 * SnsOrganizations generated by hbm2java
 */
@Entity
@Table(name = "sns_organizations"
		, catalog = "littlecloud_branch_production"
		, uniqueConstraints = @UniqueConstraint(columnNames = { "iana_id", "sn" }))
public class SnsOrganizations extends DBObject implements java.io.Serializable {

	private Integer id;
	private int ianaId;
	private String sn;
	private String organizationId;
	private Date createdAt;
	private Date updatedAt;

	public SnsOrganizations() {
	}

	public SnsOrganizations(int ianaId, String sn, Date createdAt, Date updatedAt) {
		this.ianaId = ianaId;
		this.sn = sn;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public SnsOrganizations(int ianaId, String sn, String organizationId, Date createdAt, Date updatedAt) {
		this.ianaId = ianaId;
		this.sn = sn;
		this.organizationId = organizationId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "iana_id", nullable = false)
	public int getIanaId() {
		return this.ianaId;
	}

	public void setIanaId(int ianaId) {
		this.ianaId = ianaId;
	}

	@Column(name = "sn", nullable = false, length = 32)
	public String getSn() {
		return this.sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	@Column(name = "organization_id", length = 8)
	public String getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("SnsOrganizations [id=");
		builder.append(id);
		builder.append(", ianaId=");
		builder.append(ianaId);
		builder.append(", sn=");
		builder.append(sn);
		builder.append(", organizationId=");
		builder.append(organizationId);
		builder.append(", createdAt=");
		builder.append(createdAt);
		builder.append(", updatedAt=");
		builder.append(updatedAt);
		builder.append("]");
		return builder.toString();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ianaId;
		result = prime * result + ((sn == null) ? 0 : sn.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SnsOrganizations other = (SnsOrganizations) obj;
		if (ianaId != other.ianaId)
			return false;
		if (sn == null) {
			if (other.sn != null)
				return false;
		} else if (!sn.equals(other.sn))
			return false;
		return true;
	}
}
