package com.littlecloud.control.entity;

// Generated Sep 5, 2013 6:54:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.peplink.api.db.DBObject;

/**
 * DeviceFwUpdates generated by hbm2java
 */
@Entity
@Table(name = "device_fw_updates"
		)
public class DeviceFwUpdates extends DBObject implements java.io.Serializable {

	private int deviceId;
	private Date timestamp;
	//private Devices devices;
	private int fwUpdate;
	private int retry;

	public DeviceFwUpdates() {
	}

	public DeviceFwUpdates(Devices devices, int fwUpdate, int retry) {
		//this.devices = devices;
		this.deviceId = devices.getId();
		this.fwUpdate = fwUpdate;
		this.retry = retry;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "devices"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "device_id", unique = true, nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

//	@OneToOne(fetch = FetchType.LAZY)
//	@PrimaryKeyJoinColumn
//	public Devices getDevices() {
//		return this.devices;
//	}
//
//	public void setDevices(Devices devices) {
//		this.devices = devices;
//	}

	@Column(name = "fw_update", nullable = false)
	public int getFwUpdate() {
		return this.fwUpdate;
	}

	public void setFwUpdate(int fwUpdate) {
		this.fwUpdate = fwUpdate;
	}

	@Column(name = "retry", nullable = false)
	public int getRetry() {
		return this.retry;
	}

	public void setRetry(int retry) {
		this.retry = retry;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeviceFwUpdates [deviceId=");
		builder.append(deviceId);
		builder.append(", timestamp=");
		builder.append(timestamp);
		builder.append(", fwUpdate=");
		builder.append(fwUpdate);
		builder.append(", retry=");
		builder.append(retry);
		builder.append("]");
		return builder.toString();
	}

}
