package com.littlecloud.control.entity.report;

// Generated Jun 21, 2013 10:38:37 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Digits;

import org.hibernate.annotations.GenericGenerator;

import com.peplink.api.db.DBObject;

/**
 * DeviceLocations generated by hbm2java
 */
@Entity
@Table(name = "device_locations")
public class DeviceLocations extends DBObject implements java.io.Serializable {

	private String id;
	private int networkId;
	private Integer deviceId;
	private Date datetime;
	private Integer unixtime;
	private Float latitude;
	private Float longitude;
	private Float h_dop;

	public DeviceLocations() {
	}

	public DeviceLocations(String id, int networkId, int deviceId) {
		this.id = id;
		this.networkId = networkId;
		this.deviceId = deviceId;
	}

	public DeviceLocations(String id, int networkId, int deviceId, Date datetime, Integer unixtime, Float latitude, Float longitude,Float h_dop) {
		this.id = id;
		this.networkId = networkId;
		this.deviceId = deviceId;
		this.datetime = datetime;
		this.unixtime = unixtime;
		this.latitude = latitude;
		this.longitude = longitude;
		this.h_dop = h_dop;
	}
	
	public DeviceLocations(int networkId, int deviceId, Date datetime, Integer unixtime, Float latitude, Float longitude,Float h_dop) {
		this.networkId = networkId;
		this.deviceId = deviceId;
		this.datetime = datetime;
		this.unixtime = unixtime;
		this.latitude = latitude;
		this.longitude = longitude;
		this.h_dop = h_dop;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "network_id", nullable = false)
	public int getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(int networkId) {
		this.networkId = networkId;
	}

	@Column(name = "device_id", nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "unixtime")
	public Integer getUnixtime() {
		return this.unixtime;
	}

	public void setUnixtime(Integer unixtime) {
		this.unixtime = unixtime;
	}

	@Column(name = "latitude", precision=12, scale=6)
	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision=12, scale=6)
	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}
	
	@Column(name = "h_dop", precision=12, scale=6)
	public Float getHdop() {
		return this.h_dop;
	}

	public void setHdop(Float h_dop) {
		this.h_dop = h_dop;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeviceLocations [id=");
		builder.append(id);
		builder.append(", networkId=");
		builder.append(networkId);
		builder.append(", deviceId=");
		builder.append(deviceId);
		builder.append(", datetime=");
		builder.append(datetime);
		builder.append(", unixtime=");
		builder.append(unixtime);
		builder.append(", latitude=");
		builder.append(latitude);
		builder.append(", longitude=");
		builder.append(longitude);
		builder.append(", h_dop=");
		builder.append(h_dop);
		builder.append("]");
		return builder.toString();
	}

}
