package com.littlecloud.control.entity;

// Generated Jul 26, 2013 2:53:06 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Parameter;

import com.peplink.api.db.DBObject;

/**
 * ConfigurationRadios generated by hbm2java
 */
@Entity
@Table(name = "configuration_radios"
		)
public class ConfigurationRadios extends DBObject implements java.io.Serializable {

	private ConfigurationRadiosId id;
	//private int networkId;
	private Date timestamp;
	//private Networks networks;
	private int country;
	private String protocol;
	private String bitRate;
	private String defaultBand;

	public ConfigurationRadios() {
	}

	public ConfigurationRadios(ConfigurationRadiosId id, Networks networks, int country, String protocol, String bitRate, String defaultBand) {
		//this.networks = networks;
		this.id = id;
		this.country = country;
		this.protocol = protocol;
		this.bitRate = bitRate;
		this.defaultBand = defaultBand;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "deviceId", column = @Column(name = "device_id", nullable = false)),
			@AttributeOverride(name = "networkId", column = @Column(name = "network_id", nullable = false)) })
	public ConfigurationRadiosId getId() {
		return id;
	}

	public void setId(ConfigurationRadiosId id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

//	@OneToOne(fetch = FetchType.LAZY, optional = false)
//	@NotFound(action=NotFoundAction.IGNORE)
//	@PrimaryKeyJoinColumn
//	public Networks getNetworks() {
//		return this.networks;
//	}
//
//	public void setNetworks(Networks networks) {
//		this.networks = networks;
//	}

	@Column(name = "country", nullable = false)
	public int getCountry() {
		return this.country;
	}

	public void setCountry(int country) {
		this.country = country;
	}

	@Column(name = "protocol", nullable = false, length = 45)
	public String getProtocol() {
		return this.protocol;
	}

	public void setProtocol(String protocol) {
		this.protocol = protocol;
	}

	@Column(name = "bit_rate", nullable = false, length = 45)
	public String getBitRate() {
		return this.bitRate;
	}

	public void setBitRate(String bitRate) {
		this.bitRate = bitRate;
	}

	@Column(name = "default_band", nullable = false, length = 45)
	public String getDefaultBand() {
		return this.defaultBand;
	}

	public void setDefaultBand(String defaultBand) {
		this.defaultBand = defaultBand;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ConfigurationRadios [id=");
		builder.append(id);
		builder.append(", timestamp=");
		builder.append(timestamp);
		builder.append(", country=");
		builder.append(country);
		builder.append(", protocol=");
		builder.append(protocol);
		builder.append(", bitRate=");
		builder.append(bitRate);
		builder.append(", defaultBand=");
		builder.append(defaultBand);
		builder.append("]");
		return builder.toString();
	}

}
