package com.littlecloud.control.entity.report;

// Generated Oct 16, 2013 4:33:40 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.littlecloud.control.entity.report.DeviceGpsLocationsId;
import com.peplink.api.db.DBObject;

/**
 * DeviceGpsLocations generated by hbm2java
 */
@Entity
@Table(name = "device_gps_locations")
public class DeviceGpsLocations extends DBObject implements java.io.Serializable {

	private DeviceGpsLocationsId id;
	private Date datetime;
	private Float latitude;
	private Float longitude;
	private Float altitude;
	private Float speed;
	private Float HUncertain;
	private Float VUncertain;
	private Float HDop;
	private Integer type;


	public DeviceGpsLocations() {
	}

	public DeviceGpsLocations(DeviceGpsLocationsId id) {
		this.id = id;
	}

	public DeviceGpsLocations(DeviceGpsLocationsId id, Date datetime,
			Float latitude, Float longitude, Float altitude, Float speed,
			Float HUncertain, Float VUncertain, Float HDop, Integer type) {
		this.id = id;
		this.datetime = datetime;
		this.latitude = latitude;
		this.longitude = longitude;
		this.altitude = altitude;
		this.speed = speed;
		this.HUncertain = HUncertain;
		this.VUncertain = VUncertain;
		this.HDop = HDop;
		this.type = type;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "networkId", column = @Column(name = "network_id", nullable = false)),
			@AttributeOverride(name = "deviceId", column = @Column(name = "device_id", nullable = false)),
			@AttributeOverride(name = "unixtime", column = @Column(name = "unixtime", nullable = false)) })
	public DeviceGpsLocationsId getId() {
		return this.id;
	}

	public void setId(DeviceGpsLocationsId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	@Column(name = "latitude", precision = 12, scale = 6)
	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 12, scale = 6)
	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	@Column(name = "altitude", precision = 12, scale = 6)
	public Float getAltitude() {
		return this.altitude;
	}

	public void setAltitude(Float altitude) {
		this.altitude = altitude;
	}

	@Column(name = "speed", precision = 12, scale = 6)
	public Float getSpeed() {
		return this.speed;
	}

	public void setSpeed(Float speed) {
		this.speed = speed;
	}
	
	@Column(name = "h_uncertain", precision = 12, scale = 6)
	public Float getHUncertain() {
		return this.HUncertain;
	}

	public void setHUncertain(Float HUncertain) {
		this.HUncertain = HUncertain;
	}

	@Column(name = "v_uncertain", precision = 12, scale = 6)
	public Float getVUncertain() {
		return this.VUncertain;
	}

	public void setVUncertain(Float VUncertain) {
		this.VUncertain = VUncertain;
	}

	@Column(name = "h_dop", precision = 12, scale = 6)
	public Float getHDop() {
		return this.HDop;
	}

	public void setHDop(Float HDop) {
		this.HDop = HDop;
	}
	
	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeviceGpsLocations [id=");
		builder.append(id);
		builder.append(", datetime=");
		builder.append(datetime);
		builder.append(", latitude=");
		builder.append(latitude);
		builder.append(", longitude=");
		builder.append(longitude);
		builder.append(", altitude=");
		builder.append(altitude);
		builder.append(", speed=");
		builder.append(speed);
		builder.append(", HUncertain=");
		builder.append(HUncertain);
		builder.append(", VUncertain=");
		builder.append(VUncertain);
		builder.append(", HDop=");
		builder.append(HDop);
		builder.append(", type=");
		builder.append(type);
		builder.append("]");
		return builder.toString();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DeviceGpsLocations other = (DeviceGpsLocations) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	
}
