package com.littlecloud.control.entity;

// Generated Jul 29, 2013 5:43:32 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.peplink.api.db.DBObject;

/**
 * ClientIpMacMappingsId generated by hbm2java
 */
@Embeddable
public class ClientIpMacMappingsId extends DBObject implements java.io.Serializable {

	private int networkId;
	private int deviceId;
	private String ip;

	public ClientIpMacMappingsId() {
	}

	public ClientIpMacMappingsId(int networkId, int deviceId, String ip) {
		this.networkId = networkId;
		this.deviceId = deviceId;
		this.ip = ip;
	}

	@Column(name = "network_id", nullable = false)
	public int getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(int networkId) {
		this.networkId = networkId;
	}

	@Column(name = "device_id", nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "ip", nullable = false, length = 45)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientIpMacMappingsId))
			return false;
		ClientIpMacMappingsId castOther = (ClientIpMacMappingsId) other;

		return (this.getNetworkId() == castOther.getNetworkId())
				&& (this.getDeviceId() == castOther.getDeviceId())
				&& ((this.getIp() == castOther.getIp()) || (this.getIp() != null
						&& castOther.getIp() != null && this.getIp().equals(
						castOther.getIp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNetworkId();
		result = 37 * result + this.getDeviceId();
		result = 37 * result + (getIp() == null ? 0 : this.getIp().hashCode());
		return result;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ClientIpMacMappingsId [networkId=");
		builder.append(networkId);
		builder.append(", deviceId=");
		builder.append(deviceId);
		builder.append(", ip=");
		builder.append(ip);
		builder.append("]");
		return builder.toString();
	}
}
