package com.littlecloud.control.entity;

// Generated Jul 26, 2013 2:53:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.peplink.api.db.DBObject;

/**
 * ConfigurationRadioChannels generated by hbm2java
 */
@Entity
@Table(name = "configuration_radio_channels"
		)
public class ConfigurationRadioChannels extends DBObject implements java.io.Serializable {

	private ConfigurationRadioChannelsId id;
	private Date timestamp;
	//private Devices devices;
	private String channel;
	private String power;
	private boolean boost;
	private String frequencyBand;

	public ConfigurationRadioChannels() {
	}

	public ConfigurationRadioChannels(ConfigurationRadioChannelsId id, Devices devices, String channel, String power, boolean boost, String frequencyBand) {
		this.id = id;
		//this.devices = devices;
		this.channel = channel;
		this.power = power;
		this.boost = boost;
		this.frequencyBand = frequencyBand;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "deviceId", column = @Column(name = "device_id", nullable = false)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)) })
	public ConfigurationRadioChannelsId getId() {
		return this.id;
	}

	public void setId(ConfigurationRadioChannelsId id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "device_id", nullable = false, insertable = false, updatable = false)
//	public Devices getDevices() {
//		return this.devices;
//	}
//
//	public void setDevices(Devices devices) {
//		this.devices = devices;
//	}

	@Column(name = "channel", nullable = false, length = 10)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "power", nullable = false, length = 10)
	public String getPower() {
		return this.power;
	}

	public void setPower(String power) {
		this.power = power;
	}

	@Column(name = "boost", nullable = false)
	public boolean isBoost() {
		return this.boost;
	}

	public void setBoost(boolean boost) {
		this.boost = boost;
	}

	@Column(name = "frequency_band", nullable = false, length = 45)
	public String getFrequencyBand() {
		return this.frequencyBand;
	}

	public void setFrequencyBand(String frequencyBand) {
		this.frequencyBand = frequencyBand;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ConfigurationRadioChannels [id=");
		builder.append(id);
		builder.append(", timestamp=");
		builder.append(timestamp);
		builder.append(", channel=");
		builder.append(channel);
		builder.append(", power=");
		builder.append(power);
		builder.append(", boost=");
		builder.append(boost);
		builder.append(", frequencyBand=");
		builder.append(frequencyBand);
		builder.append("]");
		return builder.toString();
	}

}
