package com.littlecloud.control.entity;

// Generated Jul 26, 2013 2:53:06 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.peplink.api.db.DBObject;

/**
 * ConfigurationSsidsId generated by hbm2java
 */
@Embeddable
public class ConfigurationSsidsId extends DBObject implements java.io.Serializable {

	private int networkId;
	private int deviceId;
	private int ssidId;

	public ConfigurationSsidsId() {
	}

	public ConfigurationSsidsId(int networkId, int ssidId, int deviceId) {
		this.networkId = networkId;
		this.deviceId = deviceId;
		this.ssidId = ssidId;
	}

	@Column(name = "network_id", nullable = false)
	public int getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(int networkId) {
		this.networkId = networkId;
	}

	@Column(name = "ssid_id", nullable = false)
	public int getSsidId() {
		return this.ssidId;
	}

	public void setSsidId(int ssidId) {
		this.ssidId = ssidId;
	}
	
	@Column(name = "device_id", nullable = false)
	public int getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfigurationSsidsId))
			return false;
		ConfigurationSsidsId castOther = (ConfigurationSsidsId) other;

		return (this.getNetworkId() == castOther.getNetworkId())
				&& (this.getSsidId() == castOther.getSsidId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNetworkId();
		result = 37 * result + this.getSsidId();
		return result;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ConfigurationSsidsId [networkId=");
		builder.append(networkId);
		builder.append(", deviceId=");
		builder.append(deviceId);
		builder.append(", ssidId=");
		builder.append(ssidId);
		builder.append("]");
		return builder.toString();
	}
}
