package com.littlecloud.control.entity;

// Generated Jul 26, 2013 2:53:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.peplink.api.db.DBObject;

/**
 * ConfigurationPepvpnCertificates generated by hbm2java
 */
@Entity
@Table(name = "configuration_pepvpn_certificates"
		)
public class ConfigurationPepvpnCertificates extends DBObject implements java.io.Serializable {

	private ConfigurationPepvpnCertificatesId id;
	private Date timestamp;
	private boolean autogen;
	private String publicKeyChecksum;
	private String publicKey;
	private String privateKey;
	private String privateKeyPass;

	public ConfigurationPepvpnCertificates() {
	}

	public ConfigurationPepvpnCertificates(ConfigurationPepvpnCertificatesId id, boolean autogen, String publicKeyChecksum, String publicKey, String privateKey, String privateKeyPass) {
		this.id = id;
		this.autogen = autogen;
		this.publicKeyChecksum = publicKeyChecksum;
		this.publicKey = publicKey;
		this.privateKey = privateKey;
		this.privateKeyPass = privateKeyPass;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "networkId", column = @Column(name = "network_id", nullable = false)),
			@AttributeOverride(name = "deviceId", column = @Column(name = "device_id", nullable = false)) })
	public ConfigurationPepvpnCertificatesId getId() {
		return this.id;
	}

	public void setId(ConfigurationPepvpnCertificatesId id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "autogen", nullable = false)
	public boolean isAutogen() {
		return this.autogen;
	}

	public void setAutogen(boolean autogen) {
		this.autogen = autogen;
	}

	@Column(name = "public_key_checksum", nullable = false, length = 100)
	public String getPublicKeyChecksum() {
		return this.publicKeyChecksum;
	}

	public void setPublicKeyChecksum(String publicKeyChecksum) {
		this.publicKeyChecksum = publicKeyChecksum;
	}

	@Column(name = "public_key", nullable = false, length = 4000)
	public String getPublicKey() {
		return this.publicKey;
	}

	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}

	@Column(name = "private_key", nullable = false, length = 4000)
	public String getPrivateKey() {
		return this.privateKey;
	}

	public void setPrivateKey(String privateKey) {
		this.privateKey = privateKey;
	}

	@Column(name = "private_key_pass", nullable = false, length = 45)
	public String getPrivateKeyPass() {
		return this.privateKeyPass;
	}

	public void setPrivateKeyPass(String privateKeyPass) {
		this.privateKeyPass = privateKeyPass;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ConfigurationPepvpnCertificates [id=");
		builder.append(id);
		builder.append(", timestamp=");
		builder.append(timestamp);
		builder.append(", autogen=");
		builder.append(autogen);
		builder.append(", publicKeyChecksum=");
		builder.append(publicKeyChecksum);
		builder.append(", publicKey=");
		builder.append(publicKey);
		builder.append(", privateKey=");
		builder.append(privateKey);
		builder.append(", privateKeyPass=");
		builder.append(privateKeyPass);
		builder.append("]");
		return builder.toString();
	}
}
