package com.littlecloud.control.entity;

// Generated Jul 26, 2013 6:06:55 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Parameter;

import com.peplink.api.db.DBObject;

/**
 * DeviceFeatures generated by hbm2java
 */
@Entity
@Table(name = "device_features"
		)
public class DeviceFeatures extends DBObject implements java.io.Serializable {

	private int deviceId;
	private Date timestamp;
	//private Devices devices;
	private int wifiSsid;
	private Integer mvpnLicense;
	private Integer mvpnStatus; 
	private String wan;
	private Integer wanCount;
	private String radioSupport;
	private String featureList;
	private Boolean gps_support;

	public DeviceFeatures() {
	}

	public DeviceFeatures(Devices devices) {
		//this.devices = devices;
		this.deviceId = devices.getId();
	}

	public DeviceFeatures(Devices devices, int wifiSsid, Integer mvpnLicense, String wan, Integer wanCount, String radioSupport, String featureList) {
		//this.devices = devices;
		this.deviceId = devices.getId();
		this.wifiSsid = wifiSsid;
		this.mvpnLicense = mvpnLicense;
		this.wan = wan;
		this.wanCount = wanCount;
		this.radioSupport = radioSupport;
		this.featureList = featureList;
	}
	
	/* ***add for PepvpnEndpointV2*** */
	public DeviceFeatures(Devices devices, int wifiSsid, Integer mvpnLicense, Integer mvpnStatus, String wan, Integer wanCount, String radioSupport, String featureList) {
		this.deviceId = devices.getId();
		this.wifiSsid = wifiSsid;
		this.mvpnLicense = mvpnLicense;
		this.mvpnStatus = mvpnStatus;
		this.wan = wan;
		this.wanCount = wanCount;
		this.radioSupport = radioSupport;
		this.featureList = featureList;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "devices"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "device_id", unique = true, nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

//	@OneToOne(fetch = FetchType.LAZY, optional = false)
//	@NotFound(action=NotFoundAction.IGNORE)
//	@PrimaryKeyJoinColumn
//	public Devices getDevices() {
//		return this.devices;
//	}
//
//	public void setDevices(Devices devices) {
//		this.devices = devices;
//	}

	@Column(name = "wifi_ssid")
	public int getWifiSsid() {
		return wifiSsid;
	}

	public void setWifiSsid(int wifiSsid) {
		this.wifiSsid = wifiSsid;
	}

	@Column(name = "mvpn_license")
	public Integer getMvpnLicense() {
		return this.mvpnLicense;
	}

	public void setMvpnLicense(Integer mvpnLicense) {
		this.mvpnLicense = mvpnLicense;
	}
	
//	@Column(name = "mvpn_status")
	public Integer getMvpnStatus() {
		return this.mvpnStatus;
	}

	public void setMvpnStatus(Integer mvpnstatus) {
		this.mvpnStatus = mvpnstatus;
	}

	@Column(name = "wan", length = 45)
	public String getWan() {
		return this.wan;
	}

	public void setWan(String wan) {
		this.wan = wan;
	}

	@Column(name = "wan_count")
	public Integer getWanCount() {
		return this.wanCount;
	}

	public void setWanCount(Integer wanCount) {
		this.wanCount = wanCount;
	}

	@Column(name = "radio_support", length = 3000)
	public String getRadioSupport() {
		return this.radioSupport;
	}

	public void setRadioSupport(String radioSupport) {
		this.radioSupport = radioSupport;
	}

	@Column(name = "feature_list", length = 3000)
	public String getFeatureList() {
		return this.featureList;
	}

	public void setFeatureList(String featureList) {
		this.featureList = featureList;
	}

	@Column(name = "gps_support")
	public Boolean isGps_support() {
		return gps_support;
	}

	public void setGps_support(Boolean gps_support) {
		this.gps_support = gps_support;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeviceFeatures [deviceId=");
		builder.append(deviceId);
		builder.append(", timestamp=");
		builder.append(timestamp);
		builder.append(", wifiSsid=");
		builder.append(wifiSsid);
		builder.append(", mvpnLicense=");
		builder.append(mvpnLicense);
		builder.append(", wan=");
		builder.append(wan);
		builder.append(", wanCount=");
		builder.append(wanCount);
		builder.append(", radioSupport=");
		builder.append(radioSupport);
		builder.append(", featureList=");
		builder.append(featureList);
		builder.append(", gps_support=");
		builder.append(gps_support);
		builder.append("]");
		return builder.toString();
	}
}
