package com.littlecloud.control.entity;

// Generated Jul 26, 2013 2:58:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Parameter;

import com.peplink.api.db.DBObject;

/**
 * DeviceStatus generated by hbm2java
 */
@Entity
@Table(name = "device_status"
		)
public class DeviceStatus extends DBObject implements java.io.Serializable {

	private int deviceId;
	private Date timestamp;
	//private Devices devices;
	private Integer alertedLevel;

	public DeviceStatus() {
	}

//	public DeviceStatus(Devices devices) {
//		this.devices = devices;
//	}
//
//	public DeviceStatus(Devices devices, Integer alertedLevel) {
//		this.devices = devices;
//		this.alertedLevel = alertedLevel;
//	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "devices"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "device_id", unique = true, nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

//	@OneToOne(fetch = FetchType.LAZY, optional = false)
//	@NotFound(action=NotFoundAction.IGNORE)
//	@PrimaryKeyJoinColumn
//	public Devices getDevices() {
//		return this.devices;
//	}
//
//	public void setDevices(Devices devices) {
//		this.devices = devices;
//	}

	@Column(name = "alerted_level")
	public Integer getAlertedLevel() {
		return this.alertedLevel;
	}

	public void setAlertedLevel(Integer alertedLevel) {
		this.alertedLevel = alertedLevel;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeviceStatus [deviceId=");
		builder.append(deviceId);
		builder.append(", timestamp=");
		builder.append(timestamp);
		builder.append(", alertedLevel=");
		builder.append(alertedLevel);
		builder.append("]");
		return builder.toString();
	}
}
