package com.littlecloud.control.entity;

// Generated Oct 4, 2013 4:04:40 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.peplink.api.db.DBObject;

/**
 * DevicesxtagsId generated by hbm2java
 */
@Embeddable
public class DevicesxtagsId extends DBObject implements java.io.Serializable {

	private long tagId;
	private int deviceId;

	public DevicesxtagsId() {
	}

	public DevicesxtagsId(long tagId, int deviceId) {
		this.tagId = tagId;
		this.deviceId = deviceId;
	}

	@Column(name = "tag_id", nullable = false)
	public long getTagId() {
		return this.tagId;
	}

	public void setTagId(long tagId) {
		this.tagId = tagId;
	}

	@Column(name = "device_id", nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DevicesxtagsId))
			return false;
		DevicesxtagsId castOther = (DevicesxtagsId) other;

		return (this.getTagId() == castOther.getTagId())
				&& (this.getDeviceId() == castOther.getDeviceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTagId();
		result = 37 * result + this.getDeviceId();
		return result;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DevicesxtagsId [tagId=");
		builder.append(tagId);
		builder.append(", deviceId=");
		builder.append(deviceId);
		builder.append("]");
		return builder.toString();
	}
}
