package com.littlecloud.control.entity;

// Generated Jul 26, 2013 2:53:06 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.peplink.api.db.DBObject;

/**
 * NetworkTypes generated by hbm2java
 */
@Entity
@Table(name = "network_types"
		)
public class NetworkTypes extends DBObject implements java.io.Serializable {

	private Integer id;
	private String type;

	public NetworkTypes() {
	}

	public NetworkTypes(String type) {
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("NetworkTypes [id=");
		builder.append(id);
		builder.append(", type=");
		builder.append(type);
		builder.append("]");
		return builder.toString();
	}

}
