package com.littlecloud.control.entity;

// Generated Oct 4, 2013 5:33:28 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.peplink.api.db.DBObject;

/**
 * TagsxconfigurationSsids generated by hbm2java
 */
@Entity
@Table(name = "tagsxconfiguration_ssids")
public class TagsxconfigurationSsids extends DBObject implements java.io.Serializable {

	private TagsxconfigurationSsidsId id;

	public TagsxconfigurationSsids() {
	}

	public TagsxconfigurationSsids(TagsxconfigurationSsidsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tagId", column = @Column(name = "tag_id", nullable = false)),
			@AttributeOverride(name = "networkId", column = @Column(name = "network_id", nullable = false)),
			@AttributeOverride(name = "ssidId", column = @Column(name = "ssid_id", nullable = false)) })
	public TagsxconfigurationSsidsId getId() {
		return this.id;
	}

	public void setId(TagsxconfigurationSsidsId id) {
		this.id = id;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("TagsxconfigurationSsids [id=");
		builder.append(id);
		builder.append("]");
		return builder.toString();
	}
}
