package com.littlecloud.control.webservices.util;

public enum Message {
	UNAVAILABLE,
	
	DEV_OFFLINE,
	MASTER_DEVICE_CANNOT_REMOVE,
	MASTER_DEVICE_SET,
	NO_MASTER_CONF_FOUND,
	SYNC_SUCCESSFULLY,
	CONF_NOT_SYNC,	
	
	HUB_OFFLINE,
	HUB_ZERO_LICENSE,
	MISSING_HUB_INFO,
	HUB_CANNOT_REMOVE,
	PEPVPN_NOT_CONFIG;
}
