package com.littlecloud.control.entity;

// Generated Sep 5, 2013 6:54:27 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.peplink.api.db.DBObject;

/**
 * DeviceUpdates generated by hbm2java
 */
@Entity
@Table(name = "device_updates"
		)
public class DeviceUpdates extends DBObject implements java.io.Serializable {

	private int deviceId;
	private int confUpdate;
	private String sid;
	private Date firstsave;		/* first config save time */
	private Date firstput;		/* first config_put time */
	private Date lastput;		/* last config_put sent time */
	private Date lastapply;		/* last config_put response time */	
	private int retry;
	private String detail;
	private String error;
	private String config;
	private String reason;
	private String prev_md5;
	private String md5;
	private Date timestamp;

	public DeviceUpdates() {
	}

	public DeviceUpdates(Devices devices, int confUpdate) {
		//this.devices = devices;
		this.deviceId = devices.getId();
		this.confUpdate = confUpdate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "devices"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "device_id", unique = true, nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "retry", nullable = false)
	public int getRetry() {
		return retry;
	}

	public void setRetry(int retry) {
		this.retry = retry;
	}
	
	@Column(name = "firstsave", nullable = true, length = 19)
	public Date getFirstsave() {
		return firstsave;
	}

	public void setFirstsave(Date firstsave) {
		this.firstsave = firstsave;
	}

	@Column(name = "firstput", nullable = true, length = 19)
	public Date getFirstput() {
		return firstput;
	}

	public void setFirstput(Date firstput) {
		this.firstput = firstput;
	}

	
	
	@Column(name = "detail", nullable = true, length = 3000)
	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "conf_update", nullable = false)
	public int getConfUpdate() {
		return this.confUpdate;
	}

	public void setConfUpdate(int confUpdate) {
		this.confUpdate = confUpdate;
	}
		
	@Column(name = "sid", nullable = true, length = 100)
	public String getSid() {
		return sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	@Column(name = "lastapply", nullable = true, length = 19)
	public Date getLastapply() {
		return lastapply;
	}

	public void setLastapply(Date lastapply) {
		this.lastapply = lastapply;
	}
	
	@Column(name = "lastput", nullable = true, length = 19)
	public Date getLastput() {
		return lastput;
	}

	public void setLastput(Date lastput) {
		this.lastput = lastput;
	}

	@Column(name = "config", nullable = true)
	public String getConfig() {
		return config;
	}

	public void setConfig(String config) {
		this.config = config;
	}

	@Column(name = "reason", nullable = true, length = 200)
	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}
	
	@Column(name = "prev_md5", nullable = true, length = 100)
	public String getPrev_md5() {
		return prev_md5;
	}

	public void setPrev_md5(String prev_md5) {
		this.prev_md5 = prev_md5;
	}

	@Column(name = "md5", nullable = true, length = 100)
	public String getMd5() {
		return md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	@Column(name = "error", nullable = true, length = 500)
	public String getError() {
		return error;
	}

	public void setError(String error) {
		this.error = error;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeviceUpdates [deviceId=");
		builder.append(deviceId);
		builder.append(", confUpdate=");
		builder.append(confUpdate);
		builder.append(", sid=");
		builder.append(sid);
		builder.append(", firstsave=");
		builder.append(firstsave);
		builder.append(", firstput=");
		builder.append(firstput);
		builder.append(", lastput=");
		builder.append(lastput);
		builder.append(", lastapply=");
		builder.append(lastapply);
		builder.append(", retry=");
		builder.append(retry);
		builder.append(", detail=");
		builder.append(detail);
		builder.append(", error=");
		builder.append(error);
		builder.append(", config=");
		builder.append(config);
		builder.append(", reason=");
		builder.append(reason);
		builder.append(", prev_md5=");
		builder.append(prev_md5);
		builder.append(", md5=");
		builder.append(md5);
		builder.append(", timestamp=");
		builder.append(timestamp);
		builder.append("]");
		return builder.toString();
	}
}
