package com.littlecloud.control.entity;

// Generated Jul 26, 2013 2:53:06 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.peplink.api.db.DBObject;

/**
 * ConfigurationRadioChannelsId generated by hbm2java
 */
@Embeddable
public class ConfigurationRadioChannelsId extends DBObject implements java.io.Serializable {

	private int deviceId;
	private int moduleId;

	public ConfigurationRadioChannelsId() {
	}

	public ConfigurationRadioChannelsId(int deviceId, int moduleId) {
		this.deviceId = deviceId;
		this.moduleId = moduleId;
	}

	@Column(name = "device_id", nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "module_id", nullable = false)
	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfigurationRadioChannelsId))
			return false;
		ConfigurationRadioChannelsId castOther = (ConfigurationRadioChannelsId) other;

		return (this.getDeviceId() == castOther.getDeviceId())
				&& (this.getModuleId() == castOther.getModuleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDeviceId();
		result = 37 * result + this.getModuleId();
		return result;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ConfigurationRadioChannelsId [deviceId=");
		builder.append(deviceId);
		builder.append(", moduleId=");
		builder.append(moduleId);
		builder.append("]");
		return builder.toString();
	}

}
