package com.littlecloud.control.entity.report;

// Generated Nov 8, 2013 11:02:01 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.EmbeddedId;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.peplink.api.db.DBObject;

/**
 * DailyClientSsidUsages generated by hbm2java
 */
@Entity
@Table(name = "daily_client_ssid_usages")
public class DailyClientSsidUsages extends DBObject implements java.io.Serializable {

	private DailyClientSsidUsagesId id;
	private int networkId;
	private Integer deviceId;
	private String name;
	private String bssid;
	private String essid;
	private String encryption;
	private String mac;
	private String type;
	private Date datetime;

	public DailyClientSsidUsages() {
		id = new DailyClientSsidUsagesId();
	}

	public DailyClientSsidUsages(int networkId, Integer deviceId, String name,
			String bssid, String essid, String encryption, String mac,
			String type, Date datetime, int unixtime) {
		id = new DailyClientSsidUsagesId();
		id.setUnixtime(unixtime);
		this.networkId = networkId;
		this.deviceId = deviceId;
		this.name = name;
		this.bssid = bssid;
		this.essid = essid;
		this.encryption = encryption;
		this.mac = mac;
		this.type = type;
		this.datetime = datetime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "unixtime", column = @Column(name = "unixtime", nullable = false)) })
	public DailyClientSsidUsagesId getId() {
		return this.id;
	}

	public void setId(DailyClientSsidUsagesId id) {
		this.id = id;
	}

	@Column(name = "network_id", nullable = false)
	public int getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(int networkId) {
		this.networkId = networkId;
	}

	@Column(name = "device_id")
	public Integer getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "bssid", length = 45)
	public String getBssid() {
		return this.bssid;
	}

	public void setBssid(String bssid) {
		this.bssid = bssid;
	}

	@Column(name = "essid", length = 45)
	public String getEssid() {
		return this.essid;
	}

	public void setEssid(String essid) {
		this.essid = essid;
	}

	@Column(name = "encryption", length = 45)
	public String getEncryption() {
		return this.encryption;
	}

	public void setEncryption(String encryption) {
		this.encryption = encryption;
	}

	@Column(name = "mac", length = 45)
	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Integer getUnixtime() {
		return id.getUnixtime();
	}

	public void setUnixtime(Integer unixtime) {
		id.setUnixtime(unixtime);
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DailyClientSsidUsages [id=");
		builder.append(id);
		builder.append(", networkId=");
		builder.append(networkId);
		builder.append(", deviceId=");
		builder.append(deviceId);
		builder.append(", name=");
		builder.append(name);
		builder.append(", bssid=");
		builder.append(bssid);
		builder.append(", essid=");
		builder.append(essid);
		builder.append(", encryption=");
		builder.append(encryption);
		builder.append(", mac=");
		builder.append(mac);
		builder.append(", type=");
		builder.append(type);
		builder.append(", datetime=");
		builder.append(datetime);
		builder.append("]");
		return builder.toString();
	}

}
