package com.littlecloud.control.entity;

// Generated Jul 26, 2013 2:53:06 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.peplink.api.db.DBObject;

/**
 * ConfigurationPepvpnCertificatesId generated by hbm2java
 */
@Embeddable
public class ConfigurationPepvpnCertificatesId extends DBObject implements java.io.Serializable {

	private int networkId;
	private int deviceId;

	public ConfigurationPepvpnCertificatesId() {
	}

	public ConfigurationPepvpnCertificatesId(int networkId, int deviceId) {
		this.networkId = networkId;
		this.deviceId = deviceId;
	}

	@Column(name = "network_id", nullable = false)
	public int getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(int networkId) {
		this.networkId = networkId;
	}

	@Column(name = "device_id", nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfigurationPepvpnCertificatesId))
			return false;
		ConfigurationPepvpnCertificatesId castOther = (ConfigurationPepvpnCertificatesId) other;

		return (this.getNetworkId() == castOther.getNetworkId())
				&& (this.getDeviceId() == castOther.getDeviceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNetworkId();
		result = 37 * result + this.getDeviceId();
		return result;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ConfigurationPepvpnCertificatesId [networkId=");
		builder.append(networkId);
		builder.append(", deviceId=");
		builder.append(deviceId);
		builder.append("]");
		return builder.toString();
	}
}
