package com.littlecloud.control.entity;

// Generated Jul 19, 2013 6:17:45 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.peplink.api.db.DBObject;

/**
 * NetworkEmailNotifications generated by hbm2java
 */
@Entity
@Table(name = "network_email_notifications")
public class NetworkEmailNotifications extends DBObject implements java.io.Serializable {

	public static final String RECIPIENT_TYPE_ONE_ADMIN = "one_admin";
	public static final String RECIPIENT_TYPE_ALL_ADMIN = "all_admin";
	public static final String RECIPIENT_TYPE_EMAILS = "emails";
	public static final String RECIPIENT_TYPE_ALL_GROUP_ADMIN = "all_group_admin";
	public static final String ALERT_TYPE_DEVICE = "device";
	public static final String ALERT_TYPE_WAN = "wan";
	public static final String ALERT_TYPE_SPEEDFUSION = "speedfusion";
	public static final String ALERT_TYPE_GEOFENCES = "geofences";
	
	public static final String INFO_DELIMITED = " ";
	
	private NetworkEmailNotificationsId id;
//	private String alertType;
//	private String level;
	private Boolean enabled;
	private int offlineMin;
	private String recipientType;
	private String info;
	
	public NetworkEmailNotifications() {
	}

	
	
	
	public NetworkEmailNotifications(NetworkEmailNotificationsId id,
			Boolean enabled, int offlineMin, String recipientType, String info) {
		super();
		this.id = id;
		this.enabled = enabled;
		this.offlineMin = offlineMin;
		this.recipientType = recipientType;
		this.info = info;
	}


	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "networkId", column = @Column(name = "network_id", nullable = false)),
			@AttributeOverride(name = "alertType", column = @Column(name = "alert_type", nullable = false, length = 20)), 
			@AttributeOverride(name = "level", column = @Column(name = "level", nullable = false, length = 45)) 
			
	})
	public NetworkEmailNotificationsId getId() {
		return this.id;
	}

	public void setId(NetworkEmailNotificationsId id) {
		this.id = id;
	}
	
//	@Column(name = "alert_type", nullable = false, length = 20)
	public String getAlertType() {
		return this.id.getAlertType();
	}

	public void setAlertType(String alertType) {
		this.id.setAlertType(alertType);
	}
	
//	@Column(name = "level", nullable = false, length = 45)
	public String getLevel() {
		return this.id.getLevel();
	}

	public void setLevel(String level) {
		this.id.setLevel(level);
	}
	
	@Column(name = "enabled", nullable = true)
	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}
	
	@Column(name = "offline_min", nullable = false)
	public int getOfflineMin() {
		return this.offlineMin;
	}

	public void setOfflineMin(int offlineMin) {
		this.offlineMin = offlineMin;
	}

	@Column(name = "recipient_type", nullable = true, length = 45)
	public String getRecipientType() {
		return this.recipientType;
	}

	public void setRecipientType(String recipientType) {
		this.recipientType = recipientType;
	}

	@Column(name = "info", length = 5000)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("NetworkEmailNotifications [id=");
		builder.append(id);
		builder.append(", enabled=");
		builder.append(enabled);
		builder.append(", offlineMin=");
		builder.append(offlineMin);
		builder.append(", recipientType=");
		builder.append(recipientType);
		builder.append(", info=");
		builder.append(info);
		builder.append("]");
		return builder.toString();
	}


	
}
